<?php

use Drupal\Core\Datetime\DrupalDateTime;

/**
 * Implements hook_entity_presave().
 */
function custom_config_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  switch ($entity->bundle()) {
    // Setting the title with the value of field_date.
    //$entity->setTitle($entity->get('field_date')->value);
    // Here you modify only your day content type
    case 'circolare':
      //Prendo il valore del Tipo di CIRCOLARE(Sciopero, Assemblea, ecc...)
      $tipoCircolareId = $entity->get('field_tipologia_circolare')->target_id;
      $tipoCircolareLoad = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($tipoCircolareId);
      $tipoCircolareName = $tipoCircolareLoad->getName();
      \Drupal::messenger()->addWarning($tipoCircolareName);
      switch ($tipoCircolareName){
        case 'Assemblea Sindacale':
          $entity->set('alternate_form', TRUE);
          $entity->alternate_form_text="NON sono in servizio
          Non sono in servizio ma PARTECIPO all assemblea in oggetto
          Sono in servizio e PARTECIPO all'assemblea in oggetto
          Sono in servizio e NON PARTECIPO all'assemblea in oggetto";

          break;
        case 'Evento':
          $entity->set('alternate_form', TRUE);
          $entity->alternate_form_text="PARTECIPO
          NON Partecipo";

          break;
        case 'Sciopero':
          $entity->set('alternate_form', TRUE);
          $entity->alternate_form_text="DICHIARO la mia intenzione di ADERIRE ALLO SCIOPERO consapevole che la presente dichiarazione è irrevocabile e fa fede ai fini della trattenuta sulla busta paga
          DICHIARO la mia intenzione di NON ADERIRE ALLO SCIOPERO
          DICHIARO di NON AVER ANCORA MATURATO alcuna decisione sull'adesione o meno allo sciopero";

          break;
      }
      break;
  }
}
