custom_config_keryx.annulla_atto:
  path: '/node/{node}/annulla'
  defaults:
    _form: '\Drupal\custom_config_keryx\Form\AnnullaAttoForm'
    _title: 'Annulla atto'
  requirements:
    _custom_access: '\Drupal\custom_config_keryx\Form\AnnullaAttoForm::access'
    node: \d+
  options:
    _admin_route: TRUE
    parameters:
      node:
        type: entity:node

custom_config_keryx.regole_pubblicazione:
  path: '/admin/config/ouitoulia/keryx/regole'
  defaults:
    _form: '\Drupal\custom_config_keryx\Form\RegolePubblicazioneForm'
    _title: 'Keryx: regole di pubblicazione'
  requirements:
    _permission: 'administer site configuration'
