custom_config_keryx.regole_pubblicazione:
  title: 'Keryx: regole di pubblicazione'
  description: 'Tipologie di documento da pubblicare solo in Amministrazione Trasparente o non pubblicabili.'
  parent: ouitolia.admin
  route_name: custom_config_keryx.regole_pubblicazione
  weight: 10

custom_config_keryx.albo_storico:
  title: 'Albo storico'
  description: 'Archivio riservato degli atti con pubblicazione scaduta.'
  route_name: view.albo_storico.pagina_albo_storico
  menu_name: azioni-principali
  weight: 5
